### PR TITLE
696 click ordering

### LINKED ISSUE #696: Revise ordering of layers to make it easier to click on tax lots and points
Desired order of layering (starting with topmost layer):
- Points (e-designations and landmarks)
- Tax lots
- Everything else in descending order according to the legend menu

----

Minor issue I’ve encountered often: Whenever I try to select a specific tax lot with the mouse, it always selects the underlying zoning district or commercial overlay. 
 
For example, I tried to click for lot 31 (below, indicated by red circle) several times, but only C2-4 info appears. 
 
image001

### PR DESCRIPTION
**Pull request by allthesignals**
Fixes a regression with tooltip templating and addresses #696 by upgrading `ember-mapbox-composer` which includes a better approach to handling hover events for overlapping layers. Needs some review to see if the behavior has improved.

@hannahkates if you can find specific issues maybe GIF them or show me ways to manually test this.

Closes #696 #785 #786 

Thanks!

### CODE REVIEW

**Comment by julialucyhogan** [comment]
Looks good, and I approved the percy diffs. But this is waiting on the merge & tag of that last update to ember-mapbox-composer, right? And then another change here to bump the addone version one more time ?

**Comment by allthesignals** [comment]
> Looks good, and I approved the percy diffs. But this is waiting on the merge & tag of that last update to ember-mapbox-composer, right? And then another change here to bump the addone version one more time ?

Not sure I understand. I think these changes include a version bump to grab the necessary version of mapbox composer.

**Comment by chriswhong** [comment]
Closes #696

**Comment by allthesignals** [comment]
> Oh wonderful, just realized the supporting layers are (mostly) fixed now! Only remaining issue I'm seeing from #786 is that the points (e-designations and landmark points) aren't layered on top of tax lots, so you can't hover or click on them when zoomed in. #785 looks fully resolved.

You can if you turn off tax lots and they seem to work fine. In the [original issue,](https://github.com/NYCPlanning/labs-zola/issues/696#issuecomment-459923814) @andycochran mentioned that "tax lots should ALWAYS be the topmost layer" - so I'm confused by this.

**Comment by allthesignals** [comment]
> Hmm something a little weird is happening where lots now have multiple lot number labels Diff example: https://percy.io/NYC-Planning-Labs/zola/builds/1419006/view/93862159/1280?browser=firefox&mode=diff
> (Percy is awesome)

Yeah - I wouldn't read too much into the diffing here. These are generated screenshots, so there'll almost always be weird little artifacts here and there. It's mostly there to catch big things - so if you see a lot of red, that's usual a sign that something's up. In this case, it's probably fine - you should just verify that it's working in the branch preview.

**Comment by julialucyhogan** [comment]
> > Hmm something a little weird is happening where lots now have multiple lot number labels Diff example: https://percy.io/NYC-Planning-Labs/zola/builds/1419006/view/93862159/1280?browser=firefox&mode=diff
> > (Percy is awesome)
> 
> Yeah - I wouldn't read too much into the diffing here. The maps generate PNG images (which are there screenshottable by Percy), so there'll almost always be weird little artifacts here and there. It's mostly there to catch big things - so if you see a lot of red, that's usual a sign that something's up. In this case, it's probably fine - you should just verify that it's working in the branch preview.

Unfortunately, this is not just a Percy artifact... I'm seeing it in staging right now. That being said I think we should merge this branch to resolve all these issues, and we can address the multiple lot IDs separately. 
screen shot 2019-02-08 at 10 59 55 am

**Comment by hannahkates** [comment]
> > Oh wonderful, just realized the supporting layers are (mostly) fixed now! Only remaining issue I'm seeing from #786 is that the points (e-designations and landmark points) aren't layered on top of tax lots, so you can't hover or click on them when zoomed in. #785 looks fully resolved.
> 
> You can if you turn off tax lots and they seem to work fine. In the [original issue,](https://github.com/NYCPlanning/labs-zola/issues/696#issuecomment-459923814) @andycochran mentioned that "tax lots should ALWAYS be the topmost layer" - so I'm confused by this.

@allthesignals Andy's comment did say tax lots on top, but after we had discussed this more, we agreed points should be on top followed by tax lots. I had updated the title and description of the issue accordingly, but I think this raises an important point that we need a better way of clearly indicating the final decision on an issue vs. preserving discussion leading up to it. I feel like the description is the best place for that, so you don't have to go digging through comments, but we should discuss and agree on the preferred method.

**Pull request merged**
