### PR TITLE
309 search route com overlays

### LINKED ISSUE #309: User can click on, search for, route to Commercial Overlays. Details link to handbook info.
Need to get some summary text so we can display it on the route.

### PR DESCRIPTION
**Pull request by allthesignals**
Includes routable commercial overlays plus map-search looks for a property `coname` in the response as well as a result type `commercial-overlay`. 

Closes #309

### CODE REVIEW

**Comment by allthesignals** [comment]
Related: https://github.com/NYCPlanning/labs-zola-search-api/pull/4

**Comment by chriswhong** [comment]
I merged the PR on `labs-zola-search-api` but I don't think this is working just yet.  The commercial overlays are not clickable, and I see multiple C1-4 results in the search results (Under add map pin, which needs to be updated too)
zola___nyc s_zoning___land_use_map_and_nycplanning_labs-zola___waffle_io

**Comment by chriswhong** [comment]
Pushed some updates: 
- removed bookmarkability (we don't have it for zoning districts either).
- fixed fitbounds on search result click

Still TODO, commerical overlays should be clickable on the map

**Comment by allthesignals** [comment]
@chriswhong 

> Still TODO, commerical overlays should be clickable on the map

I'm confused, they were clickable when I made this pull request?

**Comment by allthesignals** [comment]
Alright, I think they are clickable, but there is an ordering issue - you can't click them when zoning districts are on.

**Comment by chriswhong** [comment]
Should be able to just change the order in main-map.hbs

**Comment by allthesignals** [comment]
Alright - how should this behave? Commercial overlays on top of Zd and lots?

**Comment by chriswhong** [comment]
Yes, they should be above both

**Comment by chriswhong** [comment]
New bug, when the user clicks the "Fit all" button, need to use the offset just as we do for zoning districts: https://github.com/NYCPlanning/labs-zola/blob/develop/app/routes/zoning-district.js#L24

**Comment by allthesignals** [comment]
@chriswhong let's merge when you sign off on this

**Comment by chriswhong** [comment]
As a user I am finding it annoying to have to turn off the overlays when I want to click a tax lot underneath.  Maybe the order should be lots on top, then overlays, then zones.  This effectively means that overlays are only clickable when lots are not visible (when zoomed out)

**Comment by allthesignals** [comment]
@chriswhong I'm going to punt this to you because I'm not sure what's best.

**Comment by chriswhong** [comment]
Done, I put lots on top for now, we can change it easily if needed

**Pull request merged**
