### PR TITLE
Arrow down & Enter; FlyTo address result

### LINKED ISSUE #18: Search results can't arrow down / press enter
I can't arrow down on the results or hit enter for what I've entered

### PR DESCRIPTION
**Pull request by allthesignals**
De-abstract some things (wrong direction); introduces new methods in map-search, more event handlers for keyboard strokes. main-map now has access to a general routeTo action.

Would like @andycochran's design input on arrow down highlighting. Also, please test numerous addresses to check for strange behavior.

Closes #18

### CODE REVIEW

**Comment by chriswhong** [comment]
Added a 300 pixel padding to the `fitbounds()`, conditional on whether `mainMap.selected` exists.

**Comment by chriswhong** [comment]
When selecting an "address" result, there should be a route change.  When I selected an address after having a lot already selected, the map navigates to the selected address, but the route and the data in the UI reflect the previous lot.

**Comment by allthesignals** [comment]
@chriswhong agreed, but this PR is really about the arrow key up and down and pressing enter issue - should we merge since it solves that? I'm going to open a separate issue for your comment so we can work on it separately.

**Comment by allthesignals** [comment]
Merging this since I'm not hearing any more feedback on the arrow and enter functionality.

**Pull request merged**
